path: datasets/mosquitoes/overlap  # edit to your local dataset root
train: ../train/images
val: ../valid/images

nc: 4
names: ['aedes aegypti', 'aedes albopictus', 'anopheles stephensi', 'culex pipiens']
